version: '3.8'

services:
  db:
    build: ./db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet

  backup:
    build: ./backup
    environment:
      PGUSER: devuser
      PGPASSWORD: devpass
      PGDATABASE: devdb
      PGHOST: db
    depends_on:
      - db
    volumes:
      - ./remote:/remote
      - ./backups:/backups
    networks:
      - appnet

networks:
  appnet:

volumes:
  db_data:
